node selector
-----------------------

kubectl label no <node-name> hdd:ssd

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: labelpod
  name: labelpod
spec:
  nodeSelector:    
    hdd: ssd
  containers:
  - image: kavana97/first:1.0
    name: labelpod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

-------------------------------

node Affinity

*hard 
---------
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: labelpod
  name: labelpod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hdd
            operator: In
            values: 
             - ssd
  containers:
  - image: kavana97/first:1.0
    name: labelpod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


*soft


apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: labelpod
  name: labelpod
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
         matchExpressions:
          - key: hdd
            operator: In
            values: 
             - ssd
  containers:
  - image: kavana97/first:1.0
    name: labelpod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

------------------------------------------


taint & toleration

kubectl taint no <node-name> hdd=ssd:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: taintpod
  name: taintpod
spec:
  tolerations:
    - key: hdd
      operator: Equal
      value: ssd
      effect: NoSchedule
  containers:
  - image: kavana97/first:1.0
    name: taintpod
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
----------------------------
readiness probe

kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 2
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


----------------------------------

serviceAccount & service Context

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: mysa
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    securityContext:
      capabilities:
        add:
          - "NET_ADMIN "
          - "NET_BROADCAST"
        drop:
          - "SYS_CHROOT"
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 2
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
~           